apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fluidqr-server
  namespace: fluidqr
spec:
  podSelector:
    matchLabels:
      app: fluidqrserver
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
        - port: 80
