version: '2'
services:
  fluidqrserver-app:
    image: 7lofficial/fluidqrserver:latest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATASOURCE_URL=jdbc:mysql://fluidqrserver-mysql:3306/fluidqrserver?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - LETSENCRYPT_HOST=qr.7lofficial.de
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - DB_USERNAME=fluidqruser
      - DB_PASSWORD=fluidqruserpw
      - VIRTUAL_HOST=test
    ports:
      - 127.0.0.1:8080:8080
  fluidqrserver-mysql:
    extends:
      file: mysql.yml
      service: fluidqrserver-mysql
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=git
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_URI=https://github.com/svenleonhard/server-config-public/
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_PATHS=central-config
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - ENCRYPT_KEY=fluidqr
networks:
  nginx-proxy_default:
    external: true
