version: '2'
services:
  mysql-backup:
    image: databack/mysql-backup
    user: '0'
    environment:
      - DB_SERVER=fluidqrserver-mysql
      - DB_USER=*
      - DB_PASS=*
      - DB_NAMES=fluidqrserver
      - RUN_ONE=yes
      - DB_DUMP_TARGET=/backup
    volumes:
      - ~/backup:/backup
    networks:
      - nginx-proxy_default

networks:
  nginx-proxy_default:
    external: true
