version: '2.4'
services:
  fluidqrserver-mysql:
    image: mysql:latest
    platform: linux/x86_64/v8
    # volumes:
    #     - ~/volumes/jhipster/FluidQrServer/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=fluidqruser
      - MYSQL_PASSWORD=fluidqruserpw
      - MYSQL_DATABASE=fluidqrserver
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
