apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: fluidqrserver
      context: ../../../../fluidqr-server
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
